// Icons will be dynamically mapped in Client Components

export const chapters = [
  {
    id: 1,
    slug: "squares-and-square-roots",
    name: "Squares & Square Roots",
    icon: "Square",
    color: "bg-blue-50 text-blue-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_1/viewform?embedded=true",
  },
  {
    id: 2,
    slug: "cubes-and-cube-roots",
    name: "Cubes & Cube Roots",
    icon: "Hexagon",
    color: "bg-purple-50 text-purple-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_2/viewform?embedded=true",
  },
  {
    id: 3,
    slug: "exponents-and-radicals",
    name: "Exponents & Radicals",
    icon: "Layers",
    color: "bg-orange-50 text-orange-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_3/viewform?embedded=true",
  },
  {
    id: 4,
    slug: "direct-and-inverse-variation",
    name: "Direct & Inverse Variation",
    icon: "LineChart",
    color: "bg-green-50 text-green-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_4/viewform?embedded=true",
  },
  {
    id: 5,
    slug: "profit-loss-and-discount",
    name: "Profit, Loss & Discount",
    icon: "Percent",
    color: "bg-red-50 text-red-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_5/viewform?embedded=true",
  },
  {
    id: 6,
    slug: "compound-interest",
    name: "Compound Interest",
    icon: "Calculator",
    color: "bg-yellow-50 text-yellow-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_6/viewform?embedded=true",
  },
  {
    id: 7,
    slug: "algebraic-identities",
    name: "Algebraic Identities",
    icon: "BookOpen",
    color: "bg-indigo-50 text-indigo-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_7/viewform?embedded=true",
  },
  {
    id: 8,
    slug: "polynomials",
    name: "Polynomials",
    icon: "Layers",
    color: "bg-pink-50 text-pink-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_8/viewform?embedded=true",
  },
  {
    id: 9,
    slug: "linear-equation-in-one-variable",
    name: "Linear Equation in One Variable",
    icon: "LineChart",
    color: "bg-cyan-50 text-cyan-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_9/viewform?embedded=true",
  },
  {
    id: 10,
    slug: "parallel-lines",
    name: "Parallel Lines",
    icon: "Layers", // Placeholder
    color: "bg-teal-50 text-teal-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_10/viewform?embedded=true",
  },
  {
    id: 11,
    slug: "understanding-quadrilaterals",
    name: "Understanding Quadrilaterals",
    icon: "Square",
    color: "bg-rose-50 text-rose-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_11/viewform?embedded=true",
  },
  {
    id: 12,
    slug: "construction-of-quadrilaterals",
    name: "Construction of Quadrilaterals",
    icon: "Triangle", // Placeholder
    color: "bg-emerald-50 text-emerald-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_12/viewform?embedded=true",
  },
  {
    id: 13,
    slug: "introduction-to-graphs",
    name: "Introduction to Graphs",
    icon: "ChartBar",
    color: "bg-sky-50 text-sky-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_13/viewform?embedded=true",
  },
  {
    id: 14,
    slug: "mensuration",
    name: "Mensuration",
    icon: "Circle",
    color: "bg-fuchsia-50 text-fuchsia-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_14/viewform?embedded=true",
  },
  {
    id: 15,
    slug: "statistics-and-probability",
    name: "Statistics & Probability",
    icon: "PieChart",
    color: "bg-amber-50 text-amber-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_15/viewform?embedded=true",
  },
  {
    id: 16,
    slug: "rotational-symmetry",
    name: "Rotational Symmetry",
    icon: "Circle", // Placeholder
    color: "bg-lime-50 text-lime-600",
    googleFormLink: "https://docs.google.com/forms/d/e/1FAIpQLScP_placeholder_16/viewform?embedded=true",
  },
];

export const leaderboardData = [
  { id: 1, name: "Rahul Kumar", chapter: "Squares & Square Roots", score: 10, date: "2025-05-01" },
  { id: 2, name: "Priya Sharma", chapter: "Compound Interest", score: 10, date: "2025-05-02" },
  { id: 3, name: "Aman Verma", chapter: "Mensuration", score: 9, date: "2025-05-03" },
  { id: 4, name: "Sneha Gupta", chapter: "Polynomials", score: 9, date: "2025-05-04" },
  { id: 5, name: "Rohan Das", chapter: "Statistics & Probability", score: 8, date: "2025-05-05" },
];
